Factsheet für die Clusteranalyse
FOM-ifes/Factsheets pull request #1
Opened 2024-08-27 10:09 UTC by statistical-thinking

2024-08-27 16:26 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Beobchtete Fälle werden \textbf{in zwei oder mehrere Gruppen} (sog. Cluster) eingeteilt.
Rechtschreibfehler. "Beobachtete" ...

2024-08-27 16:27 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Die Einteilung in Cluster erfolgt dabei über das Vorhandensein von \textbf{Ähnlichkeiten zwischen den Fällen} bzw. die Abwesenheit von Ähnlichkeiten zwischen den Fällen.
Mmm ... grummel ...

2024-08-27 16:29 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Hierzu ein \textbf{einfaches Beispiel}: Wenn Kinder zu Jugendlichen heranwachsen, erhalten diese in der Regel mehr Taschengeld (bspw. ab dem 16. Geburtstag). In einem Scatterplot, basierend auf
Streudiagramm statt Scatterplot?

2024-08-27 16:30 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Vereinfacht ausgedrückt ist ein Algorithus ein \textbf{Rechenvorgang} nach einem bestimmten und sich \textbf{wiederholenden Schema}.
Was ein Algorithmus (denk an das "m" !) müssen wir nicht unbedingt hier schreiben, oder?

2024-08-27 16:31 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Schema des k-Means Algorithmus: Die Fälle werden in eine \textbf{Anzahl k an Clustern} eingeteilt, so dass die Summe der quadrierten Abweichungen von den \textbf{ClusterSchwerpunkten} (hier bes
Wenn ein Algorithmus ein Schema darstellt, was ist dann ein Schema eines Algorithmuses?

2024-08-27 16:33 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Rückgriff auf das \textbf{vorherige Beispiel}: Wenn ein Kind fälschlicherweise dem Cluster der Jugendlichen zugeordnet werden würde, würden seine \textit{Körpergröße in cm} und sein \textit{Tas
"bei den Jugendlichen _sonst_ der Fall wäre" vielleicht besser? -- Wobei mensch über das "sonst" wirklich diskutieren könnte.

2024-08-27 16:34 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Zentral für die Einteilung in die Cluster ist die vorherige Bestimmung der Anzahl k an Clustern; Dies erfolgt in der Regel über die \textbf{Within Cluster Sum of Squares}.
Nach einem ";" schreiben wir doch klein weiter, oder?

2024-08-27 16:35 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item \textbf{Alternative Algorithmen} sind bspw. \textit{k-Median} und \textit{k-Means++}.
Alternativ oder Weitere ? -- Alternativ würde ja implizieren, dass sie das selbe Ergebnis haben. :-P

2024-08-27 16:36 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\end{itemize}
Hier wäre auch der Gegenteilige Aspekt (wenn der Wert groß ist ...) sinnvoll?

"beieinander" schreibt sich "bei einander" oder?

2024-08-27 16:37 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Schritt 2: Für jedes Cluster wird das \textbf{Zentrum berechnet}, das als der durchschnittliche Wert aller Datenpunkte innerhalb des Clusters definiert ist.
Ähm, das Zentrum ist also der durchschnittliche Wert alles Datenpunkte innerhalb des Clusters ... War das kein Punkt, sondern ein Skalar? ;-)

2024-08-27 16:38 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\begin{aligned}
Wofür hier eine aligned-Umgebung?

2024-08-27 16:38 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Schritt 5: Die Fälle werden dabei so lange neuen Clustern zugewiesen, bis die Summe der quadratischen Abweichungen \textbf{minimiert} ist.
Welche Fälle nun schon wieder?

2024-08-27 16:39 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Die Within Cluster Sum of Squares führt nicht immer zu einer \textbf{optimalen Anzahl k} an Clustern.
Was ist eine optimale Anzahl in dem Kontext?

2024-08-27 16:39 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item \textbf{Überschneidungen} können zu falschen CLusterzuordnungen führen, bspw. ein überdurchschnittlich groß gewachsenes Kind mit einem ebenfalls überdurchschnittlichen Taschengeld wird der Grup
Clusterzuordnungen nicht _CL_uster ..

2024-08-27 16:40 UTC, NMarkgraf commented on Clusteranalyse.Rnw
> +\item Jeder Fall wird einem Cluster zugeordnet, so dass \textbf{keine Möglichkeit zur Ausreißerdetektion} besteht (alternativer Algorithmus: \textit{DBSCAN}).
Warum ist der Hinweis hier wichtig?

2024-08-27 16:41 UTC, NMarkgraf requested changes
Braucht noch ein paar Änderungen, denke ich, daher RC!

2024-08-27 18:15 UTC, statistical-thinking commented
Schnell und zielführend, wie immer :-) Danke! Habe parallel die Comments von Karsten eingepflegt.

2024-08-28 05:36 UTC, luebby commented
Vielen Dank!

Ich verstehe das auch gerade nicht was wo steht - halte es aber für gut möglich, dass ich was falsch gemacht habe.

Ein paar kurze Hinweise:
- Vielleicht Unsupervised Learning dick und EDA in Klammern?
- Das Beispiel hat sich in den Überschneidungen noch versteckt.
- Ich würde die mögliche Zufälligkeit der Zuordnung erwähnen. Vielleicht zumindest als Schritt 0: Es werden k zufällige Beobachtungen als Clusterzentren gewählt?

2024-08-28 07:53 UTC, merged